Sprint14
SergeyMishakov/java-shareit pull request #2
Opened 2023-03-29 01:02 UTC by SergeyMishakov

2023-03-29 20:56 UTC, db-exp requested changes

2023-03-29 20:56 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +public interface BookingRepository extends JpaRepository<Booking, Long> {
не хватает аннотации Repository

2023-03-29 20:56 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/Booking.java
>   * TODO Sprint add-bookings.
лишний комментарий

2023-03-29 20:56 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            throw new NotFoundException();
можно orElseThrow у Option использовать везде, где ты проверяешь на пустоту после получения и затем кидаешь ошибку

2023-03-29 20:56 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (itemRepository.findById(id).isEmpty()) {
можно этот if вынести в метод - часто повторяется

2023-03-29 20:56 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        return bookingService.getBookingByOwner(ownerId, state);
лучше state превратить в enum

2023-03-30 04:37 UTC, SergeyMishakov commented on src/main/java/ru/practicum/shareit/exceptions/ValidationException.java
>          }
Выполнено

2023-03-30 04:43 UTC, SergeyMishakov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>  public class ItemController {
Выполнено

2023-03-30 05:06 UTC, SergeyMishakov commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +public interface ItemRepository extends JpaRepository<Item, Long> {
Выполнено

2023-03-30 05:08 UTC, SergeyMishakov commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    private long author;
Выполнено

2023-03-30 05:12 UTC, SergeyMishakov commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +public class Comment {
Выполнено

2023-03-30 05:16 UTC, SergeyMishakov commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>  public class Item {
Выполнено

2023-03-30 05:20 UTC, SergeyMishakov commented on src/main/java/ru/practicum/shareit/user/User.java
>  public class User {
Выполнено

2023-03-30 05:21 UTC, SergeyMishakov commented on src/main/java/ru/practicum/shareit/user/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
Выполнено

2023-03-30 05:25 UTC, SergeyMishakov commented on src/main/resources/schema.sql
> +    email VARCHAR(512) NOT NULL,
Выполнено

2023-03-30 05:25 UTC, SergeyMishakov commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +public interface BookingRepository extends JpaRepository<Booking, Long> {
Выполнено

2023-03-30 05:26 UTC, SergeyMishakov commented on src/main/java/ru/practicum/shareit/booking/Booking.java
>   * TODO Sprint add-bookings.
Выполнено

2023-03-30 06:33 UTC, SergeyMishakov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            throw new NotFoundException();
Выполнено

2023-03-30 06:36 UTC, SergeyMishakov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (itemRepository.findById(id).isEmpty()) {
if заменен на orElseThrow

2023-03-30 08:23 UTC, SergeyMishakov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        return bookingService.getBookingByOwner(ownerId, state);
Выполнено

2023-03-30 08:37 UTC, SergeyMishakov commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create-drop
Выполнено

2023-03-30 09:21 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemValidator.java
> +        return name != null/* && !name.isBlank()*/;
лучше удалить в следующей итерации

2023-03-30 09:21 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemValidator.java
> +        return descr != null/* && !descr.isBlank()*/;
лучше удалить в следующей итерации

2023-03-30 09:22 UTC, db-exp approved these changes

2023-03-30 10:58 UTC, merged